### ISSUE TITLE
dropdown opens on top of floating buttons

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#17]
See included image -- the `z-index` for the dropdown (1001) is higher than that of the floating buttons (999). At the very least we should swap these, but this might also be a good time to introduce some kind of z-index management behaviour. I'm thinking down the road when there are a few different "layers" of floating things like this, plus dialogs, and we want to manage their z-indexes in an intelligent way.

![screen shot 2016-05-25 at 12 07 19 pm](https://cloud.githubusercontent.com/assets/5491151/15547397/a37cd106-2271-11e6-8065-dc56d0696b53.png)

**Comment by dbatiste** [comment]
Currently, this is the expected behavior since if the menu opened behind the floating buttons, it would make some of the menu items inaccessible with mouse, whereas the floating buttons are only covered when the menu is open.  Feel free to re-open if necessary.  :)
