### ISSUE TITLE
horizontal positioning issues

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#19]
See attached as an example. It looks like the left edge of the dropdown is being aligned with the left edge of the opener, which in this example, make the "tail" not line up.

Suggestion: no matter what "direction" the dropdown opens, **always** align the tail with the middle of the opener. Then try to centre the tail within the dropdown as well if you can, but depending on how tight things get to the right/left, the tail may need to move slightly -- but all the time staying centred with the opener.

![screen shot 2016-05-25 at 12 12 25 pm](https://cloud.githubusercontent.com/assets/5491151/15550409/51a11f96-227f-11e6-88b4-df8a9b725554.png)

**Comment by dbatiste** [comment]
I'll definitely be looking at making this smarter this sprint.  I had a brief thought though, for a context-menu opener (or other such opener) that is known to be small, the `horizontal-offset` attribute could perhaps be used until we have something more dynamic.

**Comment by dlockhart** [comment]
For sure, if you don't have anything this sprint I'll probably do something like that for the release.

**Comment by dbatiste** [comment]
Automagical positioning implemented.  Offset overrides removed.  If offset overrides are still needed it may be possible to add them, but implementation will likely be slightly different.  Ideally offset overrides are no longer needed, as they were implemented in the absence of automagical positioning.
