### ISSUE TITLE
have a default min-width

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#21]
If a dropdown is left completely empty, things get kind of ugly:

![screen shot 2016-05-26 at 11 41 18 am](https://cloud.githubusercontent.com/assets/5491151/15580751/c3ef3840-2337-11e6-902f-907cf096a29e.png)

I think a default minimum width should be set to avoid this.

**Comment by dbatiste** [comment]
This issue is fixed.
