### ISSUE TITLE
Escape from dropdown doesn't put focus on opener

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#24]
Steps to reproduce:
1. Tab to one of our openers (e.g. personal menu)
2. Press enter, dropdown opens and focus moves to the dropdown
3. Press escape, dropdown closes but focus is lost

Expected behaviour: focus should be put back on the opener.

**Comment by dbatiste** [comment]
I think this should be addressed with recent change.  I moved the logic that I had for the opener.  Basically if the active element is a child of the dropdown when it closes, the focus is moved to the opener.  As such, if the user tabs out of the dropdown, we won't be hijacking the focus on them, but if they click a menu-item or hit escape it will return focus to the opener.
