### ISSUE TITLE
Drop-down does not close in IE

### ISSUE THREAD

**Issue by capajon** [Brightspace/d2l-dropdown-ui#29]
I'm having difficulty testing this in Edge at the moment, but I assume there is a good chance it is an issue there as well.

Grafted menus in the Brightspace nav do no close automatically once open.  They do not get initial focus for some reason.  This might be a grafted menu / partial render specific issue?  It is most noticeable when opening several menus as they overlap each other.  Tabbing or otherwise setting focus on the menus, then clicking elsewhere does end up closing them.

**Comment by dbatiste** [comment]
This issue is fixed.
