### ISSUE TITLE
when dropdown contains no focusable elements, it can't be closed

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#61]
The auto-focus functionality is awesome. However, I've noticed that now if the dropdown doesn't contain any elements which are focusable, because focus never enters the dropdown it also never leaves, so it can never be "closed".

An idea: on open, if the search for the first focusable element returns nothing, maybe create an empty one and focus on that? Or do what we were doing before and focus on the dropdown itself.

@dbatiste

**Comment by dbatiste** [comment]
Hmmm.  I think I would lean towards adding a tab stop dynamically if there are no focusable elements.

The other aspect to this is that the opener currently doesn't have all the expected behavior.  When open, clicking the opener again is supposed to close the menu, and possibly if focus leaves the opener while the dropdown is open it should _probably_ also close.  This should be implemented in Polymer opener behavior.  I think this partially addresses the issue of the dropdown being stuck open, and once implemented would we still want to move the focus to said element?

**Comment by dlockhart** [comment]
That seems to make sense yeah. The advantage I see to focusing on the menu itself is that AT might read everything inside the menu at that point, which would be nice. We noticed this in the notification menus where they only contain the text "You have no messages" -- so ideally when the menu is opened, focus moves into it and that gets read. If we just created an empty element and placed focus there, nothing might get read which could be confusing.

**Comment by dbatiste** [comment]
Yeah I agree, it would be nice to have that text read by AT.

Grafting might not be done yet so we'd only want to make the container focusable after that.  So, perhaps we implement a custom `focus` method on the dropdown that will look for first focusable element, and if none exists then it applies `tabindex` to container of content (perhaps `focus(createFocusable)`)?  The consumer would still use the `no-auto-focus` attribute and would simply call `focus(true)` upon opening and after grafting.

**Comment by dlockhart** [comment]
Due to how complicated it was to get it to focus after the graft, I changed the grafting code so that it doesn't open the menu until everything is available. If the partial render happens quickly, this isn't very noticeable, and since grafting is temporary anyway, I wasn't too worried about the delay.

**Comment by dbatiste** [comment]
Ok.  So in the grating case, we'd:
* not use `no-auto-focus`
* `d2l-dropdown`'s auto focus logic would set tabindex for a containing element if no focusable element found, and focus on it

Yes?

**Comment by dlockhart** [comment]
Exactly yeah, ideally using a tabindex of `-1` so that it wouldn't normally be focusable.

**Comment by dbatiste** [comment]
Fixed as of v0.3.4.
