### ISSUE TITLE
dropdown menus should have default min and max widths

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/d2l-dropdown-ui#70]
Otherwise there's going to be a lot of inconsistencies with how people wire-up their menus.

![screen shot 2016-08-19 at 11 14 47 am](https://cloud.githubusercontent.com/assets/5491151/17814568/8030feae-65fe-11e6-973e-dc415d30de0e.png)

**Comment by dbatiste** [comment]
Default have been set (same as what the previous React version set).
